name: Self Hosted CI Template
on: workflow_call

jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          cache: "pip"
          cache-dependency-path: "setup.py"
      - run: pip install tox
      - env:
          PIP_INDEX_URL: ${{ secrets.PIP_INDEX_URL }}
        run: tox -e build
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/*
          retention-days: 1

  lint:
    needs: build
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          cache: "pip"
          cache-dependency-path: "setup.py"
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist/
      - run: pip install tox
      - env:
          PIP_INDEX_URL: ${{ secrets.PIP_INDEX_URL }}
        run: tox -e lint

  test:
    needs: build
    runs-on: [self-hosted, ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.7"
            tox-env: "py37"
          - python-version: "pypy-3.7"
            tox-env: "pypy37"
          - python-version: "3.9"
            tox-env: "py39"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "setup.py"
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist/
      - run: pip install tox
      - env:
          PIP_INDEX_URL: ${{ secrets.PIP_INDEX_URL }}
        run: tox -e ${{ matrix.tox-env }}
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: PYTHON
          files: coverage.xml
          flags: unittests
          verbose: true
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml

  publish:
    needs: [lint, test]
    if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist/
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-python-3.7-twine-4.0.0
          restore-keys: |
            pip-cache-${{ runner.os }}-python-3.7-twine-
            pip-cache-${{ runner.os }}-python-
      - run: pip install "twine==4.0.0"
      - env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload --repository-url ${{ secrets.PYPI_REPOSITORY }} dist/*
